const photos = [
  {image: 'PHOTOS/GVH-2.png',
   eventType: 'STAKEHOLDER MEETING',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Entry protocol</strong>',
   description: 'Agreement meeting with GVH <strong>Chigoneka</strong>',
   author: 'By <strong>John Mwafulirwa</strong>'
  },
   //If we want each some items to have their specific info, we should learn classes & inheritance in simp.dev 18:52:52
  {image: 'resized images/GVH Chigoneka and Jonathan .png',
   eventType: 'STAKEHOLDER MEETING',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Entry protocol</strong>',
   description: 'Agreement meeting with GVH <strong>Chigoneka</strong>',
   author: 'By <strong>John Mwafulirwa</strong>'
  },
  {image: 'PHOTOS/GVH-2.png',
   eventType: 'STAKEHOLDER MEETING',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Entry protocol</strong>',
   description: 'Agreement meeting with GVH <strong>Chigoneka</strong>',
   author: 'By <strong>John Mwafulirwa</strong>'
  },
  {image: 'resized images/GVH Chigoneka and Jonathan .png',
   eventType: 'STAKEHOLDER MEETING',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Entry protocol</strong>',
   description: 'Agreement meeting with GVH <strong>Chigoneka</strong>',
   author: 'By <strong>John Mwafulirwa</strong>'
  },
  {image: 'resized images/Sensitisational session by Jonathan.png',
   eventType: 'AWARENESS CAMPAIGNS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Community meeting </strong>',
   description: 'Senstization session at <strong>Jeziwadi</strong> Village',
   author: 'By <strong>Jonathan John</strong>'
  },
  {image: 'resized images/Sensitisational session by Frida.png',
   eventType: 'AWARENESS CAMPAIGNS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Community meeting </strong>',
   description: 'Senstization session at <strong>Jeziwadi</strong> Village',
   author: 'By <strong>Fridajie B. Mulwafu</strong>'
  },
  {image: 'resized images/Sensitizational by Atupele.png',
   eventType: 'AWARENESS CAMPAIGNS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Community meeting </strong>',
   description: 'Senstization session at <strong>Jeziwadi</strong> Village',
   author: 'By <strong>Atupele K. Sichali</strong>' 
  },
  {image: 'resized images/Role play.png',
   eventType: 'AWARENESS CAMPAIGNS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Role play </strong>',
   description: 'Role play by <strong>Teenage mothers</strong> Jeziwadi Village',
   author: 'By <strong>Teenage mothers</strong>' 
  },
  {image: 'resized images/community dialogue.png',
   eventType: 'AWARENESS CAMPAIGNS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Community meeting </strong>',
   description: 'Community dialogue session at <strong>Jeziwadi</strong> village',
   author: 'By <strong> Frank  K. Mlowoka</strong>'
  },
  {image: 'resized images/Dancers.png',
   eventType: 'AWARENESS CAMPAIGNS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Entertainment</strong>',
   description: '<strong>Youth dancers</strong> from Jeziwadi village dancing to entertain the audience',
   author: 'By <strong> Young Youth dancers</strong>'
  },
  {image: 'resized images/group.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Formation of Teenage mother groups</strong>',
   description: 'Names of five groups created includes:<strong>Peace, Proud, Tiyanjane, Thamamndo and Maziko</strong> group',
   author: 'By <strong>Project Team</strong>'
  },
  {image: 'resized images/Group counselling session.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Communication and parenting skills session</strong>',
   description: 'Psychosocial counselor providing therapy on<strong>parenting</strong> group',
   author: 'By <strong>Madam Paranjeta</strong>'
  },
  {image: 'resized images/Teen mom skills.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Financial literacy</strong>',
   description: 'Teenage mother showcasing her <strong>business product</strong>',
   author: 'By <strong>Teenage mother</strong>'
  },
  {image: 'resized images/showcas.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Financial literacy</strong>',
   description: 'Teenage mothers showcasing thier <strong>business products</strong>',
   author: 'By <strong>Teenage mothers</strong>'
  },
  {image: 'resized images/showcasing.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Financial literacy</strong>',
   description: 'Teenage mothers showcasing thier <strong>business products</strong>',
   author: 'By <strong>Teenage mothers</strong>'
  },
  {image: 'resized images/show case.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Financial literacy</strong>',
   description: "Teenage mothers' group leaders showcasing thier <strong>business products</strong>",
   author: "By <strong>Teenage mothers group Chairs</strong>"
  },
  {image: 'resized images/Business by teen mother.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Financial literacy</strong>',
   description: "Soap making",
   author: "By <strong>Teenage mother</strong>"
  },
  {image: 'resized images/Chief advisor2.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Mentorship session</strong>',
   description: 'Mentorship session at VH <strong>Jeziwadi</strong>',
   author: 'By <strong>Chief Advisor</strong>'
  },
  {image: 'resized images/Child protection leader.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Mentorship session</strong>',
   description: 'Mentorship session at VH <strong>Jeziwadi</strong>',
   author: 'By <strong>Madam Mlotha</strong> Mother group Chair'
  },
  {image: 'resized images/mentorship session Social worker.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Mentorship session</strong>',
   description: 'Mentorship session at VH <strong>Jeziwadi</strong>',
   author: 'By <strong> Madam Paranjeta </strong> Social worker' 
  },
  {image: 'resized images/Psychosocial counsellor.png',
   eventType: 'ESTABLISHMENT OF SUPPORT NETWORKS',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Mentorship session</strong>',
   description: 'Mentorship session at VH <strong>Jeziwadi</strong>',
   author: 'By <strong>Madam Paranjeta</strong> Psychosocial counsellor'
  },
  {image: 'resized images/Counselling session by Atupe.png',
   eventType: 'ACCESS TO COUNSELLING SERVICES',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Counselling service</strong>',
   description: 'Project team member providing counselling service to teenage mother',
   author: 'By <strong> Atupele A. Sichali</strong>' 
  },
  {image: 'resized images/Counselling session.png',
   eventType: 'ACCESS TO COUNSELLING SERVICES',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Counselling service</strong>',
   description: 'Project team member providing counselling service to teenage mother',
   author: 'By <strong> John Mwafulirwa</strong>' 
  },
  {image: 'resized images/Counselling session by Frank.PNG',
   eventType: 'ACCESS TO COUNSELLING SERVICES',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Counselling services</strong>',
   description: 'Project team member providing counselling service to teenage mother',
   author: 'By <strong>Frank K. Mlowoka</strong>' 
  },
  {image: 'resized images/HOme visit.jpg',
   eventType: 'ACCESS TO COUNSELLING SERVICES',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Counselling service</strong>',
   description: "Two project team members and psychosocial counselor providing counselling service to teenage mother's family",
   author: 'By <strong>Psychosocial counselor and project team members</strong>' 
  },
  {image: 'resized images/Atu educational session .png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Educational session</strong>',
   description: "Motivating parents and chiefs to continue giving education support to teen mothers",
   author: 'By <strong>Atupere K. Sichali</strong>' 
  },
  {image: 'resized images/Education session by fridah.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Educational session</strong>',
   description: "Project memeber educating parents and chiefs to continue giving education support to teen mothers",
   author: 'By <strong>Fridajie B. Mulwafu</strong>' 
  },
  {image: 'resized images/Education session by Atupele.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong>Educational session</strong>',
   description: "Project memeber educating parents and chiefs to continue giving education support to teen mothers",
   author: 'By <strong>Atupele Sichali</strong>' 
  },
  {image: 'resized images/Empowerment by Frank.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Empowering Parents and NGO's</strong>",
   description: "Empowering parents to continue giving education support to teen mothers",
   author: 'By <strong>Frank K. Mlowoka</strong>' 
  },
  {image: 'resized images/Empowerment by Para.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Empowering Parents and NGO's</strong>",
   description: "Social worker empowering parents to continue giving education support to teen mothers",
   author: 'By <strong>Madam Paranjeta</strong>' 
  },
  {image: 'resized images/Empowerment session by Fridah.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Empowering Parents and NGO's</strong>",
   description: "Empowering parents to continue giving education support to teen mothers",
   author: 'By <strong>Fridah B. Mulwafu</strong>' 
  },
  {image: 'resized images/Empowerment by atupele.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Empowering Parents and NGO's</strong>",
   description: "Project memeber educating parents and chiefs to continue giving education support to teen mothers",
   author: 'By <strong>Atupele Sichali</strong>' 
  },
  {image: 'resized images/Feild supervisor  empowerment session.png',
   eventType: 'ADVOCATE FOR EDUCATION SUPPORT TO TEENAGE MOTHER',
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Empowering Parents and NGO's</strong>",
   description: "Field supervisor empowering parents to continue giving education support to teen mothers",
   author: 'By <strong> Madam Paranjeta</strong>' 
  },
  {image: 'resized images/home vis.jpg',
   eventType: "STRENGTHENING FAMILY AND PARTNER'S SUPPORT",
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Door to door visit</strong>",
   description: "Restoring relationships of disrupted families of teenage mother",
   author: 'By <strong>Blessings Chaomba</strong>' 
  },
  {image: 'resized images/Home vis.png',
   eventType: "STRENGTHENING FAMILY AND PARTNER'S SUPPORT",
   profilePic: 'PHOTOS/Icon.png',
   title: "<strong>Session for educate partners</strong>",
   description: "providing education to teenage mothers' partners on the challenges faced and solutions",
   author: 'By <strong>Blessings Chaomba and Fridajie Mulwafu</strong>' 
  },
  {image: 'PHOTOS/supervision (2).png',
   eventType: 'SUPERVISION BY THE DEPARTMENT',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Supervision</strong>',
   description: 'Official supervision day',
   author: 'By <strong> Head of department</strong>' 
  },
  {image: 'resized images/Community meeting.png',
   eventType: 'FINAL COMMUNITY MEETING',
   profilePic: 'PHOTOS/Icon.png',
   title: '<strong> Farewell meeting with the villagers</strong>',
   description: 'Official supervision day',
   author: 'By <strong> Project team</strong>' 
  },
  //Other photos are reserved for image slider
];